# Site
repository: Jaeminst/jaeminst.github.io
favicon: images/icon.ico

# Content configuration version
version: 2

# Personal info
name: 이재민
title: Junior DevOps Engineer
email: jm1225@kakao.com
phone: 010-9900-1225
website: velog.io/@jm1225
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Jaeminst
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jaeminst
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  DevOps 엔지니어로 제 2의 인생에 도전하는 '이재민' 입니다.

  유연한 사고를 바탕으로 다양한 상황에 대처해야 하는 DevOps 의 포지션에서 새로운 것을 즐기고, 많은 사람들과의 커뮤니케이션을 즐기는 저의 강점으로 전분야의 개발자들을 화합하는 아름다운 개발문화를 만들고 싶습니다.

content:

  - title: People say about me # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠 부트캠프
        sub_title: DevOps 1기 페어/팀 리뷰
        caption: 2022.02 ~ 2022.06
        description: | # this will include new lines to allow paragraphs
          스텝 바이 스텝으로 속도 맞춰서 진행 하는 방식이나 조곤조곤한 설명이 좋습니다.

          평소에 본인이 하고 계신 것과 알고 있는 것을 잘 공유해주시고 커뮤니케이션도 원할합니다.

          모르는 것을 질문하면 적극적으로 알려줍니다.

          든든하고, 같이 과제를 진행하는 입장에서 제가 이해가 안되는 부분은 설명을 잘해줍니다.

          생각하시는 흐름을 따라가는건 재미있고, 깊이에 감탄하며 같이하다가 보면 같이 성장하는 느낌을 줍니다.

          페어 뿐만 아니라 주변 동료까지 잘 챙기셨고, 주어진 것만 하고 끝내는 것이 아니라 다른 것도 이것저것 시도해보며 스스로 학습하시는 점이 좋습니다.
          
          편안한 분위기에서 과제를 진행할 수 있게 해주었고, 자기 에러가 아닌데도 같이 고민하고 애써 주었습니다.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: 회사명
  #       link: https://google.com
  #       sub_title: DevOps Engineer
  #       caption: 2022.02 ~ 현재
  #       quote: >
  #         노베이스로 시작하는 개발자 학습서비스
  #       description: | # this will include new lines to allow paragraphs
  #         * 여기에 내용을 리스트
  #         * 하면 된다요~!

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          * AWS 클라우드 서비스를 이용한 인프라 구성 가능
          * Terraform을 통한 IaC 구현 가능
          * Shell Script로 자동화 구현 가능
          * Docker를 통한 애플리케이션을 컨테이너화 가능
          * k8s를 통한 컨테이너 오케스트레이션 가능
          * K6를 통한 서비스 성능 테스트 가능
          * Prometheus, Grafana를 통한 모니터링 구축 가능
          * MySQL, MongoDB를 활용한 WAS 구축 가능
          * Linux, Windows 운영 가능
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          * Javascript, NodeJS 이용한 3tier WAS 구축 가능
          * SDK 이용한 기능구현 가능
      - layout: left
        title: Etc
        description: | # this will include new lines to allow paragraphs
          * MS Excel
          * Lisp, ahk

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ONE SIZE 쇼핑몰
        link: velog.io/@jm1225/G-Team-Project
        # link_text: Project Website
        additional_links:
          - title:  Jaeminst/devops-01-P1-TeamG
            icon: fab fa-github
            url: github.com/Jaeminst/devops-01-P1-TeamG
        quote: >
          HTTP 프로토콜을 이해하고 API 설계 방법 학습하여 웹 서비스 작성
        description: | # this will include new lines to allow paragraphs
          * 프로젝트를 시작하며 우리가 어떤 서비스를 하고싶은지와 어떻게 백엔드를 구축할지를 논의
          * 화이트보드에 ERD를 작성한다음 DB의 구조를 정하고, fastify를 이용해 서버앱 코딩
          * 코드를 하나씩 써내려가면서 동작 원리가 궁금하여 어디서부터 가져오고 보내주고 코드들의 구조를 파악

      - layout: left
        title: AWS ECS CI/CD
        link: velog.io/@jm1225/AWS-ECS-CICD-pjt
        # link_text: Project Website
        additional_links:
          - title:  Jaeminst/devops-01-P2-TeamH
            icon: fab fa-github
            url: github.com/Jaeminst/devops-01-P2-TeamH
        quote: >
          AWS ECS, Docker 기반으로 클라우드에 애플리케이션 배포 실습
        description: | # this will include new lines to allow paragraphs
          * 아키텍처 기준으로 CI/CD를 구현하고 DNS로 Frontend와 Backend를 서비스하는 프로젝트
          * 프로젝트 초반에 팀원의 Laptop으로 협업 후 주말에 백엔드 API 서버 코딩을 진행
          * 진행 하면서, ssm 관련 문제를 만났는데 프로젝트 기간에 해결할 수 없었습니다.
          * 그러나, 프로젝트 기간이 끝난 후 [ssm trouble-shooting](https://velog.io/@jm1225/AWS-ssm-parameter-trouble-shooting)을 추가 포스팅 하였습니다.

      - layout: left
        title: AWS MSA
        link: velog.io/@jm1225/AWS-MSA-pjt
        # link_text: Project Website
        # additional_links:
        #   - title:  Jaeminst/project3-microservices
        #     icon: fab fa-github
        #     url: github.com/Jaeminst/project3-microservices
        quote: >
          Serverless 기반의 마이크로 서비스 아키텍처 완성 및 실제 구현
        description: | # this will include new lines to allow paragraphs
          * "자동 재고 확보 시스템" 을 위한 MSA를 구성하는 것을 목표로 하였습니다.
          * DAY1
            * Serverless 기반 legacy 시스템 배포 및 테스트 구현
            * SQS 이용하여 Producer-Consumer 구조 개발 구현
            * SNS-SQS 환경에서, SNS 발행서버 구현
            * 마이크로서비스 시나리오 환경구성
          * DAY2
            * 성능 테스트
            * Dead Letter Queue(DLQ) 구현
            * 다이어그램 작성
            * Sales API 배포
            * Stock Empty 람다 배포
          * DAY3
            * 공장 api REST API 문서 배포를 자동화 하기
            * 공장서버의 콜백 메시지를 받아 재고를 추가하는 람다를 구현하기

      - layout: left
        title: 화물 용달 예약/조회 앱
        link: velog.io/@jm1225/테라폼으로-만드는-EC2에-환경변수-안전하게-전달하기
        # link_text: 테라폼으로 만드는 EC2에 환경변수 안전하게 전달하기
        additional_links:
          - title:  Jaeminst/devops-01-Final-TeamG
            icon: fab fa-github
            url: github.com/Jaeminst/devops-01-Final-TeamG
        quote: >
          소비자가 예약을 하고 조회할 수 있도록 기본적인 3tier Architechure로 dev환경을 구성함.
        description: | # this will include new lines to allow paragraphs
          * 파이널 프로젝트(5/17~6/7, 3주)
          * 소비자가 상차지/하차지 등의 운송 정보를 입력하고 요금을 확인 후, 플랫폼을 통해 요청이 드라이버에게 전달 되는 서비스
          * 예약 API 서버는 AutoScaling & ELB를 적용하여 가용성과 확장성 보장
          * 예약 서버와 알림 서버는 느슨한 결합을 적용하여 장애 확산 방지
          * 데이터 보안을 위한 서브넷팅 필수
          * 빠른 조회가 가능하도록 ElastiCache(Redis) 적용
          * 데이터베이스의 내구성을 위한 다중 AZ 적용
          * 분석을 위해 Elastic Search를 통한 예약정보 logging
          * Terraform으로 구성한 인프라를 코드로 구현

  - title: Opensource # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: 개인 블로그
        link: https://velog.io/@jm1225
        quote: >
          개인 기술 블로그
        description: | # this will include new lines to allow paragraphs
          * 트러블슈팅, 습득기술 정리, 회고록 등을 공유하기 위한 블로그
          * 부트캠프 시작과 함께 블로그를 개설하여 꾸준히 블로깅

      - layout: left
        title: AWS-Configure-Register-Script
        link: https://github.com/Jaeminst/AWS-Configure-Register-Script
        quote: >
          AWS 자격증명과 프로필관리를 한 번에!
        description: | # this will include new lines to allow paragraphs
          * AWS 관련 CDK를 사용할 때, 자격증명을 편하게 해줍니다.
          * 간편하게 프로필과 리전을 설정할 수 있습니다.
          * 프로필 생성과 여러가지 기능을 추가할 예정입니다.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 코드스테이츠 부트캠프
        caption: 2022.02 ~ 2022.06
        sub_title: DevOps 1기
        quote: >
          클라우드 서비스 운영과 개발을 한번에! DevOps 부트캠프

        description: | # this will include new lines to allow paragraphs
          * [[수강생 인터뷰] 비전공자에서 개발자로 커리어 전환을 꿈꾸는 이재민님 인터뷰](https://velog.io/@jm1225/수강생-인터뷰-비전공자에서-개발자로-커리어-전환을-꿈꾸는-이재민님-인터뷰)
          * DevOps에 대한 명확한 정의를 이해
          * NodeJS 및 개발 환경 구축
          * 리눅스 운영체제
          * 웹서비스 개발 기초지식
          * Git과 버전관리 시스템
          * Web Apllication Server
          * 네트워크 기초
          * Amazon Web Service
          * Docker
          * YAML
          * 지속적 통합
          * 배포 자동화
          * 마이크로서비스
          * 마이크로서비스 작성
          * Infra as Code
          * 컨테이너 오케스트레이션
          * 서비스 모니터링
          * 성능 테스트

      - layout: left
        title: 울산과학대학
        caption: 2010.03 ~ 2012.02
        sub_title: 기계공학 전문학사
        quote: >
          설계 전공, 추가활동 사항
        description: | # this will include new lines to allow paragraphs
          * 2011.06 ~ 2011.12 / 성진지오텍 기술교육원 수료, 담수 플랜트 설계
          * 2011.09 ~ 2011.12 / 울산천사들의합창 운영진, 자원봉사 및 기부

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      보안 및 네트워크에 대한 관심과 함께 다른 관심과 취미는 다음과 같습니다.
      - 리액트 관련 학습
      - 드라마 시청

      Look at this beautiful night on the han river  
      ![Han River](images/Ttukseom-Island.jpg "Han River")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
